import com.plugtree.spotplug.impl.GenericEvent;
import java.lang.Number;

declare GenericEvent
    @role(event)
    @timestamp(callDateTime)
    @duration(callDuration)    
end

# 1st Fraud Pattern
rule "Strange volume in transaction"
dialect "mvel" 

when
then
end

# 2nd Fraud Pattern
rule "Transaction at unusual hours"

when
	$e : GenericEvent(callDateTime.hours >= 10, callDateTime.hours <=19, amount > 4000) from entry-point GenericEventEntryPoint
	
then
	$e.setProbabilidadFraude(30);	
	System.out.println("Unusual hours" + "Nombre: " + $e.getName() + " - ProbabilidadFraude: "+ $e.getProbabilidadFraude() + "%");
end

# 3th Fraud Pattern
rule "Same transaction, same time, everyday"
dialect "mvel" 

when
	GenericEvent($time : callDateTime) from entry-point GenericEventEntryPoint
	GenericEvent(callDateTime.hours == $time.hours, callDateTime.minutes == $time.minutes, callDateTime.days != $time.days) 
then
	System.out.println("Same transaction different day");
end

# 4th Fraud Pattern
rule "Incorrect Message Order"

when
	$e : GenericEvent($n : name , $sid : sequentialID, $ecdt : callDateTime) from entry-point GenericEventEntryPoint
	GenericEvent(name == $n, this != $e, sequentialID <= $sid, callDateTime >= $ecdt) from entry-point GenericEventEntryPoint
then
	System.out.println("FRAUD!- Incorrect Message Order, User = " + $n);
end

# 5th Fraud Pattern
rule "Identical transactions"
dialect "mvel" 

when
	#Bug, se llama multiples veces...
	#No estoy teniendo en cuenta la ventana de tiempo.
	$firstEvent : GenericEvent() from entry-point GenericEventEntryPoint
	GenericEvent(this != $firstEvent, this.name == $firstEvent.name, this.amount == $firstEvent.amount) from entry-point GenericEventEntryPoint
then
	System.out.println("Identical Transactions!");
	#Eliminar la transaccion.
end

# 6th Fraud Pattern
rule "Exact coincidence of 2 events at Start Time Stamp , same User"

when
	$e : GenericEvent($n : name, $ecdt : callDateTime) from entry-point GenericEventEntryPoint
	GenericEvent(name == $n, this != $e, callDateTime == $ecdt) from entry-point GenericEventEntryPoint
then
	System.out.println("FRAUD!- 2 Events at the same time, User = " + $n);
end

# 7th Fraud Pattern
rule "Too many events in a short period of time"

when
	#Bug1: Imprime una vez por evento, dado que cada evento llama a esta regla una vez.
	$firstEvent : GenericEvent() from entry-point GenericEventEntryPoint
	Number($count : intValue, intValue > 3) from accumulate($event : GenericEvent(this.name == $firstEvent.name) over window:time(1m) from entry-point GenericEventEntryPoint, count($event)) 
then
	#Bug2: Si son 4 eventos -> P = 20, cuando se le agrega un evento mas, entonces P = 40!
	#Bug3: Le deberia poner probabilidad de fraude a cada evento? No, deberia ponerselo a la cuenta.
	System.out.println("MAGIC: " + $count + " events in one minute");
end

# 8th Fraud Pattern
rule "Wide Distance Between Events"

when
	 $n : Number(intValue < 3) from accumulate( $e : GenericEvent() over window:time( 2h ) from entry-point GenericEventEntryPoint ,count($e))
	
then
	System.out.println("FRAUD!- Wide Distance Between Events " + $n.intValue());
end

# 9th Fraud Pattern
rule "Excesive amount"
dialect "mvel" 

when
	$event : GenericEvent(amount > 10000) from entry-point GenericEventEntryPoint
then
	$event.setProbabilidadFraude(30);
	System.out.println("Excesive amount: " + $event.name + "Fraud probability: " + $event.probabilidadFraude);
end